# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ed Nunez
email: ed@ednunez.me
description: software developer by day . runner by night . amateur musician whatever time is left
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ednunez.me/" # the base hostname & protocol for your site
twitter_username: 
github_username:  ednunezg
facebook_username:  ednunezg
linkedin_username:  ednunezg
youtube_username:  

paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
